/**
 - GUILD_CREATE
 - GUILD_UPDATE
 - GUILD_DELETE
 - GUILD_ROLE_CREATE
 - GUILD_ROLE_UPDATE
 - GUILD_ROLE_DELETE
 - CHANNEL_CREATE
 - CHANNEL_UPDATE
 - CHANNEL_DELETE
 - CHANNEL_PINS_UPDATE
 - THREAD_CREATE
 - THREAD_UPDATE
 - THREAD_DELETE
 - THREAD_LIST_SYNC
 - THREAD_MEMBER_UPDATE
 - THREAD_MEMBERS_UPDATE *
 - STAGE_INSTANCE_CREATE
 - STAGE_INSTANCE_UPDATE
 - STAGE_INSTANCE_DELETE
*/
export const GUILDS = 1 << 0;
/**
 - GUILD_MEMBER_ADD
 - GUILD_MEMBER_UPDATE
 - GUILD_MEMBER_REMOVE
 - THREAD_MEMBERS_UPDATE *
*/
export const GUILD_MEMBERS = 1 << 1;
/**
 - GUILD_AUDIT_LOG_ENTRY_CREATE
 - GUILD_BAN_ADD
 - GUILD_BAN_REMOVE
*/
export const GUILD_MODERATION = 1 << 2;
/**
 - GUILD_EMOJIS_UPDATE
 - GUILD_STICKERS_UPDATE
 */
export const GUILD_EMOJIS_AND_STICKERS = 1 << 3;
/**
 - GUILD_INTEGRATIONS_UPDATE
 - INTEGRATION_CREATE
 - INTEGRATION_UPDATE
 - INTEGRATION_DELETE
 */
export const GUILD_INTEGRATIONS = 1 << 4;
/**
 - WEBHOOKS_UPDATE
 */
export const GUILD_WEBHOOKS = 1 << 5;
/**
 - INVITE_CREATE
 - INVITE_DELETE
 */
export const GUILD_INVITES = 1 << 6;
/**
 - VOICE_STATE_UPDATE
 */
export const GUILD_VOICE_STATES = 1 << 7;
/**
 - PRESENCE_UPDATE
 */
export const GUILD_PRESENCES = 1 << 8;
/**
 - MESSAGE_CREATE
 - MESSAGE_UPDATE
 - MESSAGE_DELETE
 - MESSAGE_DELETE_BULK
 */
export const GUILD_MESSAGES = 1 << 9;
/**
 - MESSAGE_REACTION_ADD
 - MESSAGE_REACTION_REMOVE
 - MESSAGE_REACTION_REMOVE_ALL
 - MESSAGE_REACTION_REMOVE_EMOJI
 */
export const GUILD_MESSAGE_REACTIONS = 1 << 10;
/**
 - TYPING_START
 */
export const GUILD_MESSAGE_TYPING = 1 << 11;
/**
 - MESSAGE_CREATE
 - MESSAGE_UPDATE
 - MESSAGE_DELETE
 - CHANNEL_PINS_UPDATE
 */
export const DIRECT_MESSAGES = 1 << 12;
/**
 - MESSAGE_REACTION_ADD
 - MESSAGE_REACTION_REMOVE
 - MESSAGE_REACTION_REMOVE_ALL
 - MESSAGE_REACTION_REMOVE_EMOJI
 */
export const DIRECT_MESSAGE_REACTIONS = 1 << 13;
/**
 - TYPING_START
 */
export const DIRECT_MESSAGE_TYPING = 1 << 14;

export const MESSAGE_CONTENT = 1 << 15;
/**
 - GUILD_SCHEDULED_EVENT_CREATE
 - GUILD_SCHEDULED_EVENT_UPDATE
 - GUILD_SCHEDULED_EVENT_DELETE
 - GUILD_SCHEDULED_EVENT_USER_ADD
 - GUILD_SCHEDULED_EVENT_USER_REMOVE
 */
export const GUILD_SCHEDULED_EVENTS = 1 << 16;
/**
 - AUTO_MODERATION_RULE_CREATE
 - AUTO_MODERATION_RULE_UPDATE
 - AUTO_MODERATION_RULE_DELETE
 */
export const AUTO_MODERATION_CONFIGURATION = 1 << 20;
/**
 - AUTO_MODERATION_ACTION_EXECUTION
 */
export const AUTO_MODERATION_EXECUTION = 1 << 21;
